### PR TITLE
Moved file cleanup to classTearDown

### PR DESCRIPTION
**Pull request by djalova**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by djalova** [comment]
@gilv I created a function for cleaning all files in the test directory in SwiftTestUtils. This function is called in SwiftBaseTest.classTearDown() so it runs after all tests in a class finish.

**Comment by gilv** [comment]
@djalova  currently each test create temp files. That means we can now create temp files per class ( like one per TestSwiftFileSystemLsOperations? ( currently each test there create temp files )

**Comment by djalova** [comment]
@gilv Sure, I can try to refactor most of the tests so that they do this, but I don't think it will be possible for all of them.

**Comment by gilv** [comment]
@djalova I think TestSwiftFileSystemLsOperations is very problematic. For example all tests without @TEST annotation doesn't run at all..some tests configured bad..they suppose to use createFile and not mkdirs..and the worst is that each test there creates bunch of temp files, which is wrong - it suppose to create them once per class and not per each test

**Comment by djalova** [comment]
@gilv Should I just delete these tests? Some of them don't seem applicable.

**Comment by djalova** [comment]
I think some of the tests require certain files to exist in the file system at certain times, so it's fine to create specific files at the beginning of each test. Creating all the files at the beginning of the test suite makes it much more difficult to understand what the tests are supposed be testing.

**Comment by djalova** [comment]
@gilv Can you look at this again when you're free? I'm done with the major changes.

**Comment by djalova** [comment]
@gilv Can this get merged soon? I've finished all my changes.

**Comment by gilv** [comment]
@djalova I had to modify some things. This was needed since i changed listing functionality. Can you please merge this pull request with master and see it's working?

Also, I think we should have different test packages, one for system tests and one for unitests. This will make things more clear. For example SwiftAPIClientTest seems to be just a unitest, while other classes also access object stores. Can you please refactor them into separate packages?

Thanks.

**Comment by djalova** [comment]
@gilv I think APIClientTest was the only test that didn't make use of the Swift fs operations. I also deleted TestNamesOperations since the only test it contained was replicated in TestSwiftOperations.

**Pull request merged**
