### PR TITLE
Improved README.md and Bug fix.

### PR DESCRIPTION
**Pull request by Nosfe**
Fixed some typos.
Made more clear the README.md regarding the configuration keys.
Fixed a bug in SwiftAPIClient.java that was preventing the discovery of new files/directories.

### CODE REVIEW

**Comment by gilv** [comment]
@Nosfe I observed that this patch doesn't work well in certain use cases.
For example if you run
sc.textFile("swift2d://CONTAINER.PROVIDER/one1.data")

on the Swift structure like this
CONTAINER/one1.txt
CONTAINER/one1.txt/_SUCCESS
CONTAINER/one1.txt/part-00000
CONTAINER/one1.txt/part-00001
CONTAINER/one1.txt/part-00002
CONTAINER/one1.txt/part-00003
CONTAINER/one1.txt/part-00004
CONTAINER/one1.txt/part-00005
CONTAINER/one1.txt/part-00006
CONTAINER/one1.txt/part-00007

The reason is doesn't work is that getObjectMetadata return wrong type of one1.txt
In the line  
 return new FileStatus(so.getContentLength(), so.isDirectory(), 1, blockSize,
              getLastModified(so.getLastModified()), path);

so.isDirectory() return false, while it should be true.

**Comment by gilv** [comment]
@Nosfe I have some idea why it happened. Can you copy-paste here the data source URI that you used in Spark to access your data in Swift?

**Comment by gilv** [comment]
@Nosfe May be it better if you create two pull requests instead of this one? One will contain all fixes to documentations that you find and the other bug fix? It will be easier to merge documentation fixes and work on that bug you saw.  Just a thought.. we can still use this one if you prefer not to mess with pull requests

**Comment by gilv** [comment]
@Nosfe May be  we need a new method, something isDirectory(path). Internally it should be optimized and check the best option. For example if path/_SUCCESS exists, then it was created by Spark or Hadoop like clients - and so is directory ( this cost for one HEAD ), Otherwise we can use JOSS isDirectory().. I think it also uses some HEAD.. finally if isDirectory() return false then we need to verify this and perhaps perform some additional request to perform list with prefix.

**Comment by Nosfe** [comment]
@gilv Closing this as I opened three separate pull requests that address all the problems that I found.

**Pull request closed without merging**
