### PR TITLE
Added ability to copy files in Swift

### PR DESCRIPTION
**Pull request by djalova**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by djalova** [comment]
Related to #24
@gilv @michaelfactor I made this PR after Michael's suggestion to let users copy files instead of using non-atomic rename.

**Comment by djalova** [comment]
@gilv Updated the branch with master

**Comment by gilv** [comment]
@djalova Why not to use copy from JOSS? StoredObject has copyObject(arg0, arg1); Then you can achieve all this with few lines of code.
I also think that new methods to extract host name are not needed at all if you use JOSS build in copy.

**Comment by gilv** [comment]
@djalova We already have copy() based on JOSS. It doesn't delete all data, just copy. I suggest to close this pool request and perhaps better is to improve existing copy() based on JOSS. Thanks.

**Pull request closed without merging**
