### PR TITLE
Added rename functionality

### PR DESCRIPTION
**Pull request by djalova**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by djalova** [comment]
@gilv 
This PR adds the ability to rename objects in the object store. I do this by sending an HTTP PUT request to do a server-side copy of the object, and then deleting the old object.
This currently can only copy within a single container, but I can add the ability to copy into other containers. It also only copies a single object at time. Should I add the ability to copy entire "directories"?

**Comment by djalova** [comment]
It is now possible to rename an object into a different container. However this doesn't work when using the Hadoop shell since Hadoop thinks the URIs given for the source and destination are for different file systems.

**Comment by gilv** [comment]
@djalova I don't think we need to support Hadoop shell for now. It's not intended to be usage of this driver. I think it's fine at this point, if there will be future requirement for Hadoop shell, then we can think how to handle it.

**Comment by gilv** [comment]
@djalova I think we better add check, if path starts with "_temporary" then rename will return true, without doing your rename logic.

**Comment by djalova** [comment]
@gilv Is this to prevent renaming temporary files? Shouldn't we also produce a warning or an exception?

**Comment by gilv** [comment]
@djalova Consider
/container/a/b/c1/data.txt
/container/a/b/c2/data.txt

and now someone wants to rename /container/a/ to container/e
I assume rename need to support it, but your patch doesn't handle such use case.

Also please update your code so it will use org.apache.commons.httpclient. ( see SwiftAPIDirect class )

**Comment by gilv** [comment]
@djalova We don't want to rename _temporary folder and everything starting with it. Return 'true' will be good, since upper layers will think that it renamed. No need warning. 
The whole idea of this project is how to handle those _temporary folders and avoid to create them

**Comment by djalova** [comment]
@gilv I updated this PR to use HttpClient and added tests.

**Comment by gilv** [comment]
@djalova 
Few questions:
1. What was the reason you didn't used JOSS to make rename? 
For example, see rename and copy method here https://github.com/Alluxio/alluxio/blob/master/underfs/swift/src/main/java/alluxio/underfs/swift/SwiftUnderFileSystem.java

2. Consider
/container/a/b/c1/data.txt
/container/a/b/c2/data.txt

and now someone wants to rename /container/a/ to container/e
I assume rename need to support it, but your patch doesn't handle such use case.

**Comment by djalova** [comment]
@gilv 
1. I thought it would be cleaner if I just used the REST API.
2. Calling rename() in stocator can move the file to another container.

**Comment by michaelfactor** [comment]
What should be the semantics of rename if there is a failure halfway through, i.e., after the server side copy but before the delete, or in the case of renaming a prefix, when only some of the objects under the prefix have been copied?  POSIX file system semantics would make this atomic.  What happens today in Hadoop shell?  (Asking not because we should support but to get motivation -- it likely also has some issues with ensuring atomicity.)  If we cannot make this operation atomic (which I doubt we can), can it be made idempotent (modulo other changes to the object store)?

**Comment by gilv** [comment]
@djalova @michaelfactor In addition, i just  wonder - why wee need rename in Stocator? 
Spark doesn't use it, so what is the end-client that will use Stocator and perform rename? 
Is this patch intended for Hadoop shell?

**Comment by michaelfactor** [comment]
@gilv Good question.  I was coming in in the middle and didn't realize the need was not clear.

**Comment by djalova** [comment]
@gilv This was one of the issues that Bert Van der Linden brought up during one of our discussions.

**Comment by djalova** [comment]
@michaelfactor The current swift driver in Hadoop is not atomic and if the delete fails after the copy then both copies will just remain in the container. My current implementation does not handle prefixes. By idempotent do you mean that if two rename operations with the same arguments occur within a short period of time, then the operation will effectively only occur once?

**Comment by michaelfactor** [comment]
@djalova What I was looking to achieve with idempotency was the ability of a client to recall if it did not receive response or received a server error in order to "complete" the operation, e.g., cleaning up the fact that there are two copies.  

In terms of the rationale, what is the use case for Spark for rename that is behind Bert's thinking?

**Comment by djalova** [comment]
@michaelfactor I can update the PR so that it will clean up in the case where deleting the old file fails. I will send you an email about the discussion I had with Bert.

**Comment by djalova** [comment]
@gilv I misinterpreted your earlier comment. I see what you meant now, I'll work on adding recursive naming when a directory is passed.

**Comment by gilv** [comment]
@djalova Current Swift doesn't use COPY command at all. There is no delete after COPY, since we don't use COPY. Can you point me to the code or flow that you describe?

**Comment by michaelfactor** [comment]
@djalova Since the server running the code can crash between the copy and the delete, I don't think you can assume your code will clean up in the event of a failure.   If a client fails to get a response, e.g., if a server crashes, they are likely to reissue the request; thus, the desire for idempotency, the reissue will do the cleanup.  This is not perfect and can leave around extra copies but it helps.  Of course what you suggested in terms of clean up is also important.

@gilv: @djalova comments are in reference to an implementation of Rename.  We need to still verify it is needed for the Spark use case as Stocator uses different mechanism to achieve the all or nothing behavior which is done via Rename in HDFS's default connector.

**Comment by djalova** [comment]
@gilv I meant using the copy command as a way to implement rename, like Michael said. There is a copy command in the Swift API. Here is a link to the documentation: [http://developer.openstack.org/api-ref-objectstorage-v1.html#copyObject](url)

@michaelfactor Would it be better to just implement copy and let the user call copy and delete themselves as a workaround for rename?

**Comment by michaelfactor** [comment]
@djalova My 2c is it would be better to just do COPY and let user handle delete if needed.

**Comment by gilv** [comment]
@djalova what is the status of it? Can we just implement copy and that's it? without delete? ( if i am not mistaken, it was suggested by @michaelfactor ) 
@djalova Can you please update this branch with the master and implement COPY?
Thanks

**Comment by djalova** [comment]
@gilv I implemented copy in this PR #39

**Pull request closed without merging**
