### PR TITLE
Bugfix for getStoreClient

### PR DESCRIPTION
**Pull request by djalova**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by djalova** [comment]
The original code would cause an error at runtime because the Configuration object passed to getStoreClient would actually be a org.apache.hadoop.mapred.JobConf. This causes the getConstructor() method to throw a NoSuchMethodFoundException because it expects a org.apache.hadoop.conf.Configuration. To fix this, I simply passed the correct Configuration class.

**Comment by djalova** [comment]
@gilv Have you run into these runtime exceptions? I've been getting them ever since the pluggable schema was implemented.

**Comment by gilv** [comment]
@djalova How did you managed to execute it and get org.apache.hadoop.mapred.JobConf in run-time? I just wonder how it happens, since i never saw a similar exception

**Comment by gilv** [comment]
Merged

**Comment by djalova** [comment]
@gilv I've run into the exception every time I run with spark-shell or pyspark. I haven't tried with spark-submit but I'm sure the case is the same.

**Pull request closed without merging**
