### PR TITLE
Swift Operations without Joss (WIP)

### PR DESCRIPTION
**Pull request by djalova**
Developer's Certificate of Origin 1.1

```
   By making a contribution to this project, I certify that:

   (a) The contribution was created in whole or in part by me and I
       have the right to submit it under the Apache License 2.0; or

   (b) The contribution is based upon previous work that, to the best
       of my knowledge, is covered under an appropriate open source
       license and I have the right under that license to submit that
       work with modifications, whether created in whole or in part
       by me, under the same open source license (unless I am
       permitted to submit under a different license), as indicated
       in the file; or

   (c) The contribution was provided directly to me by some other
       person who certified (a), (b) or (c) and I have not modified
       it.

   (d) I understand and agree that this project and the contribution
       are public and that a record of the contribution (including all
       personal information I submit with it, including my sign-off) is
       maintained indefinitely and may be redistributed consistent with
       this project or the open source license(s) involved.
```

### CODE REVIEW

**Comment by gilv** [comment]
@djalova I was thinking if we need the same model as JOSS has..like "Container", "Object", etc..
Another approach is just to create a class with "createObject, readObject, deleteObject, readContainer, etc..." and internally just implement it, similar to what we did in 
[SwiftAPIDirect.java](https://github.com/SparkTC/stocator/blob/master/src/main/java/com/ibm/stocator/fs/swift/SwiftAPIDirect.java)
This will be cleaner and then we can wrap each command with some retry mechanism...like token expire

**Comment by gilv** [comment]
@djalova when i think more -  i think extending SwiftAPIDirect is much simpler and cleaner... we don't need to build some generic Swift driver like JOSS which is too complicated. The "flat" design of SwfitAPIDirect has many advantages... it's better to extend it with other methods and that's it.

**Comment by djalova** [comment]
@gilv I originally did it this way so i could map each API call to a method but not all these operations are needed. I agree with your suggestion.

**Comment by gilv** [comment]
@djalova based on the previous discussion that we had - can you please move to "flat" implementation? Just extend SwiftDirectClient with HEAD, GET, etc.. and then replace relevant methods in SwiftAPIclient.

**Comment by gilv** [comment]
@djalova Let's start with HEAD. It's easiest to implement and then we can use in SwiftAPIClient

**Comment by djalova** [comment]
@gilv I was planning on doing that once I've tested all the operations. It's easier to test if a operation is working at the moment because I can just substitute my classes for the Joss classes. If I try to move now it might introduce new bugs.

**Comment by gilv** [comment]
@djalova but on the other hand you work too hard now. It's not easy to substitute classes for JOSS. I think it would be much easier to start with simple HEAD and identify what really metadata needed by SwiftAPIClient and that's it.. it would be much easier. Then you can remove JOSS to call getMetadata

**Comment by djalova** [comment]
@gilv Ok I'll try that out then.

**Pull request closed without merging**
