### PR TITLE
Unitests left _SUCCESS objects in the test containers

### PR DESCRIPTION
**Pull request by jasoncl**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by jasoncl** [comment]
I notice at the end of executing testDataObject(), the _SUCCESS object still remains in my swift server. This PR deletes the _SUCCESS object at the end of the test.

**Comment by Nosfe** [comment]
@jasoncl @gilv 
I believe the normal behaviour of Hadoop is to keep the _SUCCESS, not to delete it.
In the past it was used to check, in jobs pipeline, if the previous job was "SUCCESS".
Why would you need to remove it now? Just because there is an extra 0 bytes files in the Swift container? Is it worth?

**Comment by gilv** [comment]
@jasoncl @Nosfe I think this patch only handle unitest issue, where objects were deleted from the container and _SUCCESS was not deleted by mistake.

**Comment by Nosfe** [comment]
@jasoncl @gilv 
Ok, I havent's look at the changes.
The title of the PR was a bit misleading.

**Comment by gilv** [comment]
Merged

**Pull request closed without merging**
