### PR TITLE
Modified SwiftAPIClient.listContainer to handle wildcards

### PR DESCRIPTION
**Pull request by djalova**
Currently, an exception is thrown when you try to use a path with a wildcard such as "File*", this PR fixes this and another problem. The current implementation of listContainer will list extra files. For example, if you query for "File1" you will also get "File11" if it exists in the container. This PR fixes this so that it will only return "File1" as expected.

I'm still working on a few edge cases but feel free to review and comment.

### CODE REVIEW

**Comment by gilv** [comment]
@djalova Thanks. Does Hadoop allows to provide URI in a form "swift2d://container.service/a/b* " ?
Is this what you mean to cover in this patch?

**Comment by djalova** [comment]
@gilv Yes, I've tested URIs in that form and it works.

**Comment by djalova** [comment]
I tested the following types of queries
"swift2d://container.service/*" - List all objects in root
"swift2d://container.service/A/*" - List all objects in directory called A
"swift2d://container.service/A/*.txt" - List all objects in directory A ending with ".txt"
swift2d://container.service/A/*abc*" - List all objects in directory A that contains "abc"

**Comment by djalova** [comment]
I noticed the test annotation was missing for testSimilarNames(). I ran the test on master and noticed it failed, returning 3 FileStatuses when there was only 1 expected. I tried running it again with my patch and it worked fine.

**Comment by gilv** [comment]
@djalova Does your patch also allows to list recursive?
For recursive list you need to set
sc.hadoopConfiguration.set("mapreduce.input.fileinputformat.input.dir.recursive","true")

For example

a/b/c/d/e.data
a/b/c/d/f.data
a/b/c/d/f.data/_SUCCESS
a/b/c/d/f.data/part-1
a/b/c/d/f.data/part-2

Will swift2d://container.service/a/b* return

a/b/c/d/e.data
a/b/c/d/f.data/part-1
a/b/c/d/f.data/part-2
?

**Comment by djalova** [comment]
@gilv For that case, I don't think it will. It will at some point try to list "a/b/c/*" but the directory "a/b/c" doesn't actually exist in the container. I will try to patch this case.

**Comment by gilv** [comment]
@djalova I was reviewing your patch and then i realized that most of  'problems' came from the Globber class that is responsible for container list / objects match operations. The worst thing was that Globber is not object store oriented and generates a lot of requests, which are completely not needed.
In the last commit i introduced ObjectStoreGlobber. It's not yet ready, work in progress, but has some basic functionalities, including coverage for swift2d://container.service/* or similar, with "*".
However ObjectStoreGlobber is not yet completed, for example we need to cover things like
swift2d://container.service/a/b=12/c*/d. We also need to test it.
Can you please see it / review it / work on it? ObjectStoreGlobber is responsible for listing and should be our focus to support various listing.

**Comment by djalova** [comment]
@gilv Sure, I'll take a look at it.

**Comment by gilv** [comment]
This patch is not relevant anymore. 
There is a new patch https://github.com/SparkTC/stocator/pull/20 related listing

**Pull request closed without merging**
