### PR TITLE
Added S3 support using JetS3t.

### PR DESCRIPTION
**Pull request by hntd187**
I basically did (or attempted) to do what you outlined in the bottom of your future work. I understand this pull request is all over the place in formatting and everything, but I did manage to test it and it appears to be working correctly, but obviously this is a long way off from being anything mergable. I'd like to get the ball rolling on what you guys would like to do going forward with this to test and refactor it to stay within your design ideas.

### CODE REVIEW

**Comment by gilv** [comment]
@hntd187 Thanks, This is great!
I will review the code. Just a short question, what was the major refactoring to support S3? My initial impression was that ObjectStoreFileSystem and IStoreClient doesn't need much refactoring to support other object stores

**Comment by hntd187** [comment]
@gilv I don't think I changed anything in those classes at all, I think the only thing I updated was some of the documentation because the check-style was complaining about some of the documentation strings and I wanted to fix the warnings. I'd say overall the interface is good given an object store functions like that in the first place, but I also refrained from adding exceptions or having anything like that bubble up out of concern on breaking your contracts so I left them alone for now.

Overall though it was pretty straight forward, but there were a few things which I'm not sure if I did correctly.

1. My configuration path, I made it fs.amazon.service.s3.**** but I'm not stuck on that and it can be made to be more inline with whatever, I wasn't sure if you wanted to stay with swift2d or if you were okay with object paths being in the s3 format.

2. My actual setup of S3 Paths relative to Hadoop, they are kind of redundant and some of the system checks in place here require you to do unnecessary things, like the initial bucket URI must be s3://bucket.bucket even though this isn't necessary to s3 working, but stocator wants that format to extract the service. I didn't want to mess too much with your validation or object contracts without first submitting this as I didn't want to break some idea that you had in mind to keep this working. 

3. The underlying JetSet library whether you are reading or writing from S3 only uses input streams for communication, so some of the code is seemingly backwards because of it. Like downloading from S3 is mostly reading from an InputStream, but the uploading is the data is written to an internal OutputSteam in the class, but then when the handle is closed it will actually write that stream to the input stream necessary to upload to S3, this gets around the need to write a temporary file and check it's length because you just check the length of that stream when it's converted to a byte array, but this probably won't work well for very large files, so we'll have to test that.

**Comment by gilv** [comment]
@hntd187 Can you please add comment with this text ( with new pull requests it's added automatic ): https://github.com/SparkTC/stocator/blob/master/.github/PULL_REQUEST_TEMPLATE ?
Please also add line  at the end 
Signed-off-by: Your-Name <your-email>

**Comment by hntd187** [comment]
Where do you want this added? @gilv

**Comment by gilv** [comment]
@hntd187 just copy-paste the text into comment. see this one for example 
https://github.com/SparkTC/stocator/pull/7

I am in a process of the integration of many changes to the code. The new addition will cover all known fault tolerance issues with Spark. New code will support run time exception coverage in Spark, also support for speculative mode, including coverage  of https://issues.apache.org/jira/browse/SPARK-10063 and many other failure scenarios.
After code is merged, please rebase your pull request, You will need to add few small additions to your implementation to support fault tolerance mode.
After that -  i will be glad to review and merge your code. I think it's great addition.

**Comment by hntd187** [comment]
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

Signed-off-by: Stephen Carman shcarman@gmail.com

**Comment by hntd187** [comment]
@gilv Let me know when you are ready and I'll make my fixes for you.

**Comment by gilv** [comment]
@hntd187 I did many modifications to the code, in order to support various Spark failure scenarios. The new code covers speculate mode, run time exceptions in Spark master, etc. The new code is stable now.

While most of the new logic was added to ObjectStoreFileSystem, there is some new logic in the Swift driver. In particular "list " method has changed and include new coverage.

I assume you will need to implement the same logic for "list". Swift return list of objects, sorted by name. I think the same is true for S3. If yes, you need to adapt list logic from Swift driver to your S3 driver

Can you please refactor your code?

**Comment by hntd187** [comment]
@gilv Yup, give me some time and I can refactor for it. Hopefully it's not a lot of stuff, right?

**Comment by gilv** [comment]
@hntd187 No, it's not a lot of stuff. Most of the work was done in ObjectStoreFileSystem which is the same class for Swift and S3 implementations.

I think, only "list" should be modified in the S3 driver. May be some other minor changes. Also minor interface modifications.

**Pull request closed without merging**
