### PR TITLE
Return single file status, when globber has no path pattern (Spark Streaming fix)

### PR DESCRIPTION
**Pull request by djalova**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by djalova** [comment]
@gilv I tested this with Spark Streaming and it works. The only thing we have to change is we specify the directory as "swift2d://directory.service/" instead of "swift2d://directory.service/*"

**Comment by gilv** [comment]
@djalova I think "swift2d://directory.service/*" is fine, i am not sure we need "swift2d://directory.service/". There is no spec i think for this

**Comment by gilv** [comment]
@djalova can you please explain this pull request? We already return single file status, in

`if (candidates == null) {
        return new FileStatus[0];
      }
`

**Comment by djalova** [comment]
@gilv I think both ways should work. When you make the call you pass in the path of a directory so it should be possible to pass in a single directory path. For the second point we were actually returning a list of paths before, so I changed it to getFileStatus in case we wanted to get the file status for the root directory.

**Comment by gilv** [comment]
@djalova so what this commit changes comparing to previous code? What it improves? Thanks

**Comment by djalova** [comment]
@gilv Previously we would query for a list of FileStatuses when we only needed one. This patch is an improvement because now we only query for the FileStatus we need.
Also if`ObjectStoreGlobber.glob("swift2d://container.service/)` is ever called (without any pattern). We need to return a FileStatus for the root directory. Currently this will return the first item in the container, which is incorrect.

**Comment by gilv** [comment]
@djalova thanks. merged

**Pull request closed without merging**
