### PR TITLE
Simplified Globber logic

### PR DESCRIPTION
**Pull request by djalova**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by djalova** [comment]
@gilv Can you review this patch? I tried to simplify the logic for the Globber to remove unnecessary calls to JOSS. When using the '\*' wildcard it will list recursively by default.

**Comment by gilv** [comment]
@djalova Thanks. I will check it.

**Comment by gilv** [comment]
@djalova Can you please explain shortly what was the issue in the original code? I am trying to understand your patch. Thanks

**Comment by djalova** [comment]
Sure, the original Globber would check if the path container a wild card. If it contains one it would split the path by the "/". So "a/b/c/*" would become an array {a, b, c}. Then it would make a call to the FileSystem for all paths within the directory "a", then "a/b", then "a/b/c." For Stocator, we just need to make the last call for "a/b/c."

**Comment by djalova** [comment]
@gilv I found a few edge cases where the listing fails in the current code. If we have the following files in our container, "Dir/SubDir/FileA", "Dir/SubDir/FileB", "Dir/FileA" and do a search for "Dir/SubDir/*", the globber returns 0 results. In this patch, the globber returns 2 results for the example.

**Comment by gilv** [comment]
@djalova Thanks a lot. I will review it in the next 1-2 days.

**Comment by gilv** [comment]
@djalova Will your patch cover something like /a/b/*/c/d ?

**Comment by gilv** [comment]
@djalova if yes, can you add test for this? thanks

**Comment by gilv** [comment]
@djalova In addition, can you check please that with your patch you can write and read it back? 
val data = Array(1, 2, 3, 4, 5, 6, 7, 8)
val distData = sc.parallelize(data)
distData.saveAsTextFile("swift2d://newcontainer.SERVICE_NAME/one1.txt")

sc.textFile("swift2d://newcontainer.SERVICE_NAME/one1.txt").count()

**Comment by gilv** [comment]
@djalova Thanks. I just performed series of tests and seems your patch resolved all the issues.

**Comment by gilv** [comment]
@djalova  merged

**Pull request closed without merging**
